#!/usr/bin/env python3
"""Activation-PCA baseline row for the baseline bake-off.

This is the activation-space counterpart to ``baseline_bakeoff.py``. It loads a
base model plus matched misaligned and benign arms, collects residual activations
on a fixed prompt set, and scores held-out arms with a leave-one-seed-out PCA
direction in residual space.

The output is a real external activation artifact consumed by
``baseline_bakeoff.py --activation-pca-json``. No synthetic activation rows are
generated by the weight-space runner.
"""
import argparse
import glob
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

import numpy as np

try:
    import torch
except ModuleNotFoundError:  # Allow --help/static checks on CPU-only machines.
    torch = None

sys.path.insert(0, os.path.dirname(__file__))
from run_environment import collect_run_environment  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_SCRIPTS = ["code/activation_pca_baseline.py", "code/run_environment.py"]


def require_torch():
    if torch is None:
        raise RuntimeError("activation_pca_baseline.py requires torch and transformers")
    return torch


def relpath(path):
    p = Path(path)
    try:
        return str(p.resolve().relative_to(ROOT))
    except ValueError:
        return str(p)


def file_sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def model_files(snapshot):
    snapshot = Path(snapshot)
    patterns = [
        "model.safetensors.index.json",
        "model.safetensors",
        "*.safetensors",
        "pytorch_model.bin",
        "pytorch_model-*.bin",
        "config.json",
        "generation_config.json",
        "tokenizer.json",
        "tokenizer.model",
        "tokenizer_config.json",
        "special_tokens_map.json",
        "vocab.json",
        "merges.txt",
        "added_tokens.json",
    ]
    out = []
    for pattern in patterns:
        out.extend(snapshot.glob(pattern))
    return sorted({path for path in out if path.is_file()})


def find_snapshot(path):
    path = Path(path)
    if model_files(path):
        return path
    snapshots = sorted((path / "snapshots").glob("*"))
    complete = [snapshot for snapshot in snapshots if model_files(snapshot)]
    if len(complete) == 1:
        return complete[0]
    if len(complete) > 1:
        raise ValueError(f"{path}: ambiguous cached snapshots; pass an exact snapshot path")
    return path


def hash_model_inputs(paths):
    resolved = []
    hashes = {}
    for label, path in paths:
        snapshot = find_snapshot(path)
        resolved.append({
            "label": label,
            "requested": relpath(path),
            "snapshot": relpath(snapshot),
        })
        files = model_files(snapshot)
        if not files:
            raise FileNotFoundError(f"no model weight files found for {label}: {snapshot}")
        for file_path in files:
            hashes[relpath(file_path)] = file_sha256(file_path)
    return resolved, hashes


def write_json_atomic(path, payload):
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    tmp = out.with_name(f"{out.name}.tmp.{os.getpid()}")
    try:
        with open(tmp, "w") as f:
            json.dump(payload, f, indent=2)
            f.write("\n")
        os.replace(tmp, out)
    finally:
        if tmp.exists():
            tmp.unlink()


def git(args):
    try:
        return subprocess.check_output(["git"] + args, cwd=ROOT, text=True).strip()
    except Exception:
        return None


def git_status_for(paths):
    return git(["status", "--short", "--"] + list(paths)) or ""


def read_jsonl(path):
    rows = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def prompt_from_row(row):
    if isinstance(row, str):
        return row
    if isinstance(row, dict):
        if isinstance(row.get("messages"), list):
            return row["messages"]
        for key in ("prompt", "text", "content", "instruction", "question"):
            if isinstance(row.get(key), str):
                return row[key]
    raise ValueError(f"unsupported prompt row: {row!r}")


def load_prompt_rows(path, n_prompts, seed):
    path = Path(path)
    if path.suffix == ".jsonl":
        raw = read_jsonl(path)
    else:
        raw = json.load(open(path))
    if not isinstance(raw, list) or not raw:
        raise ValueError(f"{path}: prompt file must contain a nonempty list or JSONL rows")
    rows = [(idx, prompt_from_row(row)) for idx, row in enumerate(raw)]
    rng = np.random.default_rng(seed)
    order = rng.permutation(len(rows)).tolist()
    keep = len(rows) if n_prompts <= 0 else min(n_prompts, len(rows))
    selected = [rows[i] for i in order[:keep]]
    return selected, len(rows)


def render_prompt(tok, item):
    if isinstance(item, list):
        try:
            return tok.apply_chat_template(item, tokenize=False, add_generation_prompt=True)
        except Exception:
            return "\n".join(str(msg.get("content", "")) for msg in item if isinstance(msg, dict))
    try:
        return tok.apply_chat_template(
            [{"role": "user", "content": item}],
            tokenize=False,
            add_generation_prompt=True,
        )
    except Exception:
        return str(item)


def set_padding(tok):
    tok.padding_side = "left"
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token


def dtype_from_name(name):
    t = require_torch()
    return {
        "float32": t.float32,
        "float16": t.float16,
        "bfloat16": t.bfloat16,
    }[name]


def load_model_and_tokenizer(model_id, dtype, local_files_only):
    from transformers import AutoModelForCausalLM, AutoTokenizer

    tok = AutoTokenizer.from_pretrained(model_id, local_files_only=local_files_only)
    set_padding(tok)
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=dtype,
        local_files_only=local_files_only,
    )
    model.eval()
    return model, tok


def pool_hidden(hidden, mask, mode):
    t = require_torch()
    mask = mask.to(hidden.device)
    if mode == "last":
        return hidden[:, -1]
    weights = mask.unsqueeze(-1).to(hidden.dtype)
    denom = weights.sum(dim=1).clamp(min=1.0)
    return (hidden * weights).sum(dim=1) / denom


def collect_activations(model, tok, prompts, args, device):
    t = require_torch()
    rendered = [render_prompt(tok, item) for _, item in prompts]
    rows = []
    with t.no_grad():
        for start in range(0, len(rendered), args.batch_size):
            batch = rendered[start:start + args.batch_size]
            enc = tok(
                batch,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=args.max_length,
            ).to(device)
            out = model(**enc, output_hidden_states=True, use_cache=False)
            hidden_states = out.hidden_states
            index = args.layer + 1
            if index >= len(hidden_states):
                raise ValueError(
                    f"layer {args.layer} unavailable; model returned {len(hidden_states) - 1} layers"
                )
            pooled = pool_hidden(hidden_states[index].float(), enc["attention_mask"], args.pool)
            rows.append(pooled.detach().cpu().numpy().astype(np.float32))
    return np.concatenate(rows, axis=0)


def model_activations(model_id, prompts, args, device):
    t = require_torch()
    model, tok = load_model_and_tokenizer(model_id, dtype_from_name(args.dtype), args.local_files_only)
    model.to(device)
    try:
        return collect_activations(model, tok, prompts, args, device)
    finally:
        del model
        if device.startswith("cuda") and t.cuda.is_available():
            t.cuda.empty_cache()


def unit(vec, context):
    vec = np.asarray(vec, dtype=np.float64)
    if vec.ndim != 1:
        raise ValueError(f"{context}: expected vector, got shape {vec.shape}")
    if not np.all(np.isfinite(vec)):
        raise ValueError(f"{context}: vector contains non-finite values")
    norm = float(np.linalg.norm(vec))
    if norm <= 0.0:
        raise ValueError(f"{context}: zero-norm vector")
    return vec / norm


def top_activation_pc(delta):
    _, _, vt = np.linalg.svd(delta, full_matrices=False)
    return unit(vt[0], "activation_pca")


def activation_score(delta, direction):
    return float(np.linalg.norm(delta @ direction) / (np.linalg.norm(delta) + 1e-12))


def auc_from_scores(mis_scores, ben_scores):
    total = 0
    wins = 0.0
    for mis in mis_scores:
        for ben in ben_scores:
            total += 1
            if mis > ben:
                wins += 1.0
            elif mis == ben:
                wins += 0.5
    return float(wins / total) if total else None


def summarize_folds(folds):
    wins = sum(1 for fold in folds if fold["mis_score"] > fold["ben_score"])
    margins = [fold["mis_score"] - fold["ben_score"] for fold in folds]
    return {
        "folds": folds,
        "mis_above_ben": f"{wins}/{len(folds)}",
        "mean_margin": float(np.mean(margins)) if margins else None,
        "auc": auc_from_scores(
            [fold["mis_score"] for fold in folds],
            [fold["ben_score"] for fold in folds],
        ),
    }


def activation_pca_detection(mis_deltas, ben_deltas):
    n = min(len(mis_deltas), len(ben_deltas))
    folds = []
    for held in range(n):
        train_mis = [mis_deltas[i] for i in range(n) if i != held]
        train_ben = [ben_deltas[i] for i in range(n) if i != held]
        contrast = np.mean(train_mis, axis=0) - np.mean(train_ben, axis=0)
        direction = top_activation_pc(contrast)
        folds.append({
            "held": held,
            "mis_score": activation_score(mis_deltas[held], direction),
            "ben_score": activation_score(ben_deltas[held], direction),
        })
    return summarize_folds(folds)


def arm_paths(runs, pattern, context):
    paths = sorted(glob.glob(str(Path(runs) / pattern)))
    if not paths:
        raise FileNotFoundError(f"{context}: no arms matched {Path(runs) / pattern}")
    return paths


def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", required=True)
    ap.add_argument("--runs", default="runs")
    ap.add_argument("--misaligned-glob", required=True)
    ap.add_argument("--benign-glob", required=True)
    ap.add_argument("--prompts", required=True)
    ap.add_argument("--n-prompts", type=int, default=64)
    ap.add_argument("--min-prompts", type=int, default=64)
    ap.add_argument("--prompt-seed", type=int, default=0)
    ap.add_argument("--layer", type=int, default=12)
    ap.add_argument("--pool", choices=["mean", "last"], default="mean")
    ap.add_argument("--batch-size", type=int, default=4)
    ap.add_argument("--max-length", type=int, default=512)
    ap.add_argument("--dtype", choices=["bfloat16", "float16", "float32"], default="bfloat16")
    ap.add_argument("--device", default=None)
    ap.add_argument("--local-files-only", action="store_true")
    ap.add_argument("--min-arm-pairs", type=int, default=4)
    ap.add_argument("--out", default="results/data/activation_pca_baseline.json")
    return ap.parse_args()


def main():
    args = parse_args()
    source_git_commit = git(["rev-parse", "HEAD"])
    source_git_status_short = git_status_for(MANIFEST_SCRIPTS)
    if source_git_status_short and os.environ.get("ALLOW_DIRTY_SOURCE") != "1":
        raise RuntimeError(
            "activation-PCA source files are dirty; commit/stash them or set "
            f"ALLOW_DIRTY_SOURCE=1:\n{source_git_status_short}"
        )
    t = require_torch()
    device = args.device or ("cuda" if t.cuda.is_available() else "cpu")
    prompts, n_available_prompts = load_prompt_rows(args.prompts, args.n_prompts, args.prompt_seed)
    if len(prompts) < args.min_prompts:
        raise ValueError(
            f"selected {len(prompts)} prompts, below --min-prompts={args.min_prompts}"
        )
    if args.n_prompts > 0 and len(prompts) < args.n_prompts:
        raise ValueError(
            f"requested {args.n_prompts} prompts but only {n_available_prompts} are available"
        )
    mis_paths = arm_paths(args.runs, args.misaligned_glob, "misaligned")
    ben_paths = arm_paths(args.runs, args.benign_glob, "benign")
    if len(mis_paths) < args.min_arm_pairs or len(ben_paths) < args.min_arm_pairs:
        raise ValueError(
            f"need >= {args.min_arm_pairs} matched arms per condition; got "
            f"{len(mis_paths)} misaligned and {len(ben_paths)} benign"
        )
    overlap = sorted({str(Path(path).resolve()) for path in mis_paths} & {str(Path(path).resolve()) for path in ben_paths})
    if overlap:
        raise ValueError(f"misaligned and benign arm sets overlap: {overlap[0]}")
    n = min(len(mis_paths), len(ben_paths))
    mis_paths = mis_paths[:n]
    ben_paths = ben_paths[:n]
    provenance_inputs = (
        [("base", args.base)]
        + [(f"misaligned_{i}", path) for i, path in enumerate(mis_paths)]
        + [(f"benign_{i}", path) for i, path in enumerate(ben_paths)]
    )
    resolved_inputs, input_hashes = hash_model_inputs(provenance_inputs)

    print(f"collecting base activations: {args.base}", flush=True)
    base_acts = model_activations(args.base, prompts, args, device).astype(np.float64)
    mis_deltas = []
    ben_deltas = []
    for path in mis_paths:
        print(f"collecting misaligned activations: {path}", flush=True)
        mis_deltas.append(model_activations(path, prompts, args, device).astype(np.float64) - base_acts)
    for path in ben_paths:
        print(f"collecting benign activations: {path}", flush=True)
        ben_deltas.append(model_activations(path, prompts, args, device).astype(np.float64) - base_acts)

    payload = {
        "schema": "activation_pca_baseline_v1",
        "source": "external_activation_artifact",
        "method": "activation_pca",
        "layer": args.layer,
        "pool": args.pool,
        "score": "||v^T dA||_2 / ||dA||_F",
        "detection": activation_pca_detection(mis_deltas, ben_deltas),
        "producer": {
            "script": "code/activation_pca_baseline.py",
            "script_sha256": file_sha256(ROOT / "code" / "activation_pca_baseline.py"),
            "dependency_script_sha256": {
                "code/run_environment.py": file_sha256(ROOT / "code" / "run_environment.py"),
            },
            "source_git_commit": source_git_commit,
            "source_git_status_short": source_git_status_short,
            "git_commit": git(["rev-parse", "HEAD"]),
            "git_status_short": git(["status", "--short"]) or "",
        },
        "provenance": {
            "base": relpath(args.base),
            "runs": relpath(args.runs),
            "misaligned_glob": args.misaligned_glob,
            "benign_glob": args.benign_glob,
            "n_pairs": n,
            "prompts": relpath(args.prompts),
            "prompts_sha256": file_sha256(args.prompts),
            "requested_n_prompts": args.n_prompts,
            "n_available_prompts": n_available_prompts,
            "min_prompts": args.min_prompts,
            "n_prompts": len(prompts),
            "prompt_seed": args.prompt_seed,
            "prompt_indices": [idx for idx, _ in prompts],
            "dtype": args.dtype,
            "device": device,
            "batch_size": args.batch_size,
            "max_length": args.max_length,
            "local_files_only": bool(args.local_files_only),
            "resolved_inputs": resolved_inputs,
            "input_sha256": input_hashes,
            "environment": collect_run_environment(os.environ.get("GPU_ID")),
        },
    }
    write_json_atomic(args.out, payload)
    print(f"wrote {args.out}")


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
